<?php
/**
 * Flickr Rippr tags -- imports tags when importing photos from flickr
 */
 
/**
 * When we modify the node, get the tags
 */
function flickrtags_flickrrippr_node_alter($node, $details) {
  //TODO make the tags a hook
  if (variable_get('flickrtags_import', FALSE)) {
    $vocab = variable_get('flickrtags_vocab', 0);
    if (!$vocab) {
      return;
    }
    flickrtags_photo_add_tags($node->nid, $details);
  }
}

function flickrtags_photo_add_tags($nid, $photo_info=null) {
  if (!$nid) {
    drupal_set_message(t('Refusing to add tags to a null nid'), 'error');
    return;
  }
  $node = node_load(array('nid' => $nid));
  $vid = variable_get('flickrtags_vocab', 0);
//   $node_terms = $node->taxonomy;

  $node_terms = array();
  foreach($photo_info['tags']['tag'] as $tag) {
    $raw = $tag['raw'];
    $terms = taxonomy_get_term_by_name($raw);

    //if we got some terms back, check if they're in our vocab or not
    if (sizeof($terms)) {
      $term = flickrtags_matching_vid($terms, $vid);
    }
    
    //if we still don't have a term, create it.
    if (!isset($term) or !sizeof($terms)) {
      drupal_set_message("Creating new term $raw");
      $term = array(
        'vid' => $vid, // Voacabulary ID
        'name' => $raw, // Term Name 
        'synonyms' => $tag['_content'], // (Optional) Synonym of this term
        'relations' => array(15), // (Optional) Related Term IDs 
      );
      taxonomy_save_term($term);
      //add to those we are gonna save
    }
    $node_terms[] = $term;

  }
//   drupal_set_message("Tags = ". print_r($node_terms, 1));
  taxonomy_node_save($node, $node_terms); 
}

function flickrtags_matching_vid($terms, $vid) {
  foreach($terms as $t) {
    if ($t->vid == $vid) {
      return $t;
    }
  }
}

/**
 * Admin for, for controlling what vocab to use
 */
function flickrtags_form_alter(&$form, $form_state, $form_id) {
  if('flickrrippr_admin_settings_form' != $form_id) {
    return;
  }

  $form['tags'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tags'),
    '#collapsible' => TRUE,
    '#weight' => 0,
);
  $form['tags']['flickrtags_import'] = array(
    '#title' => t('Import tags?'), 
    '#type' => 'checkbox',
    '#default_value' => variable_get('flickrtags_import', FALSE),
  );

  $options = array();
  foreach(taxonomy_get_vocabularies() as $v) {
    $options[$v->vid] = $v->name; 
  }
  $form['tags']['flickrtags_vocab'] = array(
    '#title' => t('Vocabulary for tags'), 
    '#type' => 'select', 
    '#options' => $options,
    '#default_value' => variable_get('flickrtags_vocab', 0),
  );

  
  $form['#validate'][] = 'flickrtags_admin_validate'; 
  $form['#submit'][] = 'flickrtags_admin_submit';  

  return $form;
}

function flickrtags_admin_validate($form_id, $form_state) {
}

/**
 * Save which vocab we're using
 */
function flickrtags_admin_submit($form_id, $form_state) {
  $import_tags = $form_state['values']['flickrtags_import'];
  variable_set('flickrtags_import', $import_tags);
  
  $vocab = $form_state['values']['flickrtags_vocab'];
  variable_set('flickrtags_vocab', $vocab);  
  drupal_set_message('Flickr tags settings saved');
}