<?php

/**
 * Make visible to the Flickr Rippr module
 */
function flickrimage_flickrrippr_node_handler_options() {
  return array('flickrimage' => 'Image Module');
}

function flickrimage_flickrrippr_make_node($details) {

  
  $image_node = node_load(array('nid' => $node->flickr_photo->image_nid));
    
  //get original jpeg
  $src = flickrrippr_path_remote($image_node, 'o');
  $response = drupal_http_request($src);
  if ($response->code != 200) {
    //try again without _o
    $src = flickrrippr_path_remote($image_node, FALSE);
    $response = drupal_http_request($src);
  }

  if ($response->code != 200) {
    drupal_set_message(t('Failed to fetch jpeg from flickr. Src was %src', array('%src' => $src)), 'error');
    return flickrrippr_path_remote($image_node, $size);
  }

  $filename = $flickr_photo['id'] .'_'. $flickr_photo['secret'] . '_o.jpg';
  //jpeg is now in $response->data
  $file = file_save_data($response->data, $filename, FILE_EXISTS_REPLACE);

  if (!$file) {
    drupal_set_message(t('Failed to save file %filename', array('%filename' => $filename)), 'error');
    watchdog('flickrimage', t('Failed to save file %filename', array('%filename' => $filename)));
    return flickrrippr_path_remote($image_node, $size);
  }

//   drupal_set_message("Saving new image node");
//function image_create_node_from($filepath, $title = NULL, $body = '', $taxonomy = NULL) {
  $image_node = image_create_node_from($file, $flickr_photo['title'], $flickr_photo['description']);
  if (!$image_node) {
    drupal_set_message(t('Failed to save as an image node.'), 'error');
    $image_node->flickr_photo = $flickr_photo;
    return flickrrippr_path_remote($image_node, $size);
  }

//   drupal_set_message("linking to new image node");
  db_query("UPDATE {flickrphotos} SET image_nid=%d WHERE nid=%d", $image_node->nid, $node->nid);

  $image_node = node_load(array('nid' => $image_node->nid));
  return $image_node;
}
