<?php

/**
 * 
 */
function flickrimage_flickrrippr_path_options() {
  return array('flickrimage' => 'Image Module');
}

/**
 * implementatin of hook_flickrrippr_path
 * Save the file on the file system - not as a deep linking src to flickr.com
 */
function flickrimage_get_path($flickr_photo, $size, $node) {


  if ($node->image_nid) {
    drupal_set_message("Existing image nid found");
    return;
  }

  //get original jpeg
  $src = flickrrippr_path_remote($flickr_photo, 'o');
  $response = drupal_http_request($src);
  if ($response->code != 200) {
    drupal_set_message(t('Failed to fetch jpeg from flickr'), 'error');
    return $src;
  }

  $filename = $flickr_photo['id'] .'_'. $flickr_photo['secret'] . '_o.jpg';
  //jpeg is now in $response->data
  $file = file_save_data($response->data, $filename, FILE_EXISTS_REPLACE);

  if (!$file) {
    drupal_set_message(t('Failed to save file %filename', array('%filename' => $filename)), 'error');
    watchdog('flickrimage', t('Failed to save file %filename', array('%filename' => $filename)));
    return flickrrippr_path_remote($flickr_photo, $size);
  }

  
//function image_create_node_from($filepath, $title = NULL, $body = '', $taxonomy = NULL) {
  $image_node = image_create_node_from($file, $flickr_photo['title'], $flickr_photo['description']);
  if (!$image_node) {
    drupal_set_message(t('Failed to save as an image node.'), 'error');
    return flickrrippr_path_remote($flickr_photo, $size);
  }

  db_query("UPDATE {flickrphotos} SET image_node=%d WHERE nid=%d", $image_node->nid, $node->nid);

  return $file;
}