<?php

/**
 * Implementation of hook_menu().
 */
function flickrgroups_menu() {
  $items['flickr/groups'] = array(
    'title' => 'Flickr Groups',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'flickrgroup_admin_page',
    'access arguments' => array('administer imported flickr groups'),
    'file' => 'flickrgroups.content.inc',
  );
  $items['flickr/groups/add'] = array(
    'title' => 'Flickr Groups',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flickrgroups_admin_form'),
    'access arguments' => array('administer imported flickr groups'),
    'file' => 'flickrgroups.content.inc',
  );
//     $items['flickr/groups/%'] = array(
//     'type' => MENU_LOCAL_TASK,
//     'page callback' => 'flickrgroup_page',
//     'access arguments' => array('administer imported flickr groups'),
//     'file' => 'flickrgroups.content.inc',
//   );
  
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function flickrgroups_perm() {
  return array('administer imported flickr groups', 'view list of flickr groups');
}

function flickrgroups_get_group($flickrgroup_id) {
  return db_fetch_object(db_query("SELECT * FROM {flickrgroups} WHERE flickrgroup_id='%s'", $flickrgroup_id));
}

function flickrgroups_get_all_groups() {
  $result = db_query("SELECT * FROM {flickrgroups}");
  $groups = array();
  while ($g = db_fetch_object($result)) {
    $groups[] = $g;
  }
  return $groups;
}

function flickrgroups_fetch_group($flickrgroup_id, $force_now=FALSE) {
  drupal_set_message(t('Fetching group %id', array('%id' => $flickrgroup_id)));
  $group = flickrgroups_get_group($flickrgroup_id);
  if(!$group) {
    drupal_set_message(t("Request to fetch invalid group with id = %id", array('%id' => $flickrgroup_id)), 'error');
    return;
  }
  $flickr = flickrapi_phpFlickr();
  if (!$flickr) {
    drupal_set_message(t("Unable to query flickr.com"), 'error');
    watchdog('flickrrippr', 'Unable to query flickr.com');
  }
  
  $num_photos = variable_get('flickrrippr_num_per_fetch', 100);
  $photos = $flickr->groups_pools_getPhotos($group->flickrgroup_id, array(), null, null, $num_photos);

  $num_photos = 0;
  if (!isset($photos['photo']) || !is_array($photos['photo'])) {
    drupal_set_message(t("No photos found while querying flickr group %name", array('%name' => $group->name)));
    return;
  }
  foreach ($photos['photo'] as $p) {
    //hack to get around job_queue restricting descriptions to 255 chars
    $description = t("Save node for flickr photo %id", array('%id' => $p['id']));
    if (strlen($description) >= 255) {
      $description = substr($description, 0, 254);
    }
    drupal_set_message($description);
    if ($force_now) {
      $node = flickrrippr_makenode($p['id']);
    }
    else {
      job_queue_add('flickrrippr_makenode', $description, array($p['id']));
    }
    
    $num_photos++;
  }
  
}
function flickrgroup_debug($thing) {
  drupal_set_message(print_r($thing, 1));
}

function flickrgroup_nodeapi($node, $op) {
  if ($op == 'insert') {
    drupal_set_message(print_r($node, 1));
  }
}

function flickrgroup_page($flickrgroup_id) {
  $group = flickrgroups_get_group($flickrgroup_id);
  drupal_set_title($group->name);
  $photos = flickrgroup_get_cached_photos($flickrgroup_id);
  $output = '';
  foreach($photos as $p) {
    $output .= theme('image', flickrrippr_path($p), $p->title, $p->title);
  }
  return $output;
}

/**
 * Implementation of hook_cron().
 */
function flickrgroups_cron() {
  $result = db_query("SELECT * FROM {flickrgroups}");
  while ($group = db_fetch_object($result)) {
    flickrgroups_fetch_group($group->flickrgroup_id);
  }
}