<?php


function flickrcomments_flickrrippr_node_alter($node, $details) {
  $photo_id = $details['photo_id'];
  drupal_set_message("Going to get comments for $photo_id");
  $flickr = flickrapi_phpFlickr();
  if (!$flickr) {
    drupal_set_message(t("Unable to query flickr.com, library is missing."), 'error');
    return FALSE;
  }
  $comments = $flickr->photos_comments_getList($photo_id);
//       drupal_set_message('all = '. nl2br(print_r($comments['comment'], 1)));

  foreach($comments['comment'] as $c) {
    drupal_set_message('comment  = '. print_r($c, 1));
    $existing_comment = _flickrcomments_get_comment($c['id']);
    drupal_set_message(print_r($existing_comment, 1));
  }
}


function _flickrcomments_get_comment($comment_id) {
  return db_fetch_object(db_query("SELECT * FROM {flickrcomments} where flickrcommentid='%s'"));
  
}

