<?php

/**
 * 
 */
function flickrjpegcache_flickrrippr_path_options() {
  return array('flickrjpegcache' => 'Local Jpeg Cache');
}

/**
 * implementatin of hook_flickrrippr_path
 * Save the file on the file system - not as a deep linking src to flickr.com
 */
function flickrjpegcache_get_path($flickr_photo, $size=FALSE) {
  $src = flickrrippr_path_remote($flickr_photo, $size);
  $response = drupal_http_request($src);
  if ($response->code != 200) {
    drupal_set_message(t('Failed to fetch jpeg from flickr'), 'error');
    return $src;
  }

  $filename = $flickr_photo['flickrphoto_id'] .'_'. $flickr_photo['secret'] . ($size ? '_'. $size : '') .'.jpg';
  //jpeg is now in $response->data
  $file = file_save_data($response->data, $filename, FILE_EXISTS_REPLACE);
//   drupal_set_mes#sage(t("Jpeg saved as %file", array('%file' => $file)));
  return $file;
}