<?php

/**
 * Implementatin of hook_menu().
 */
function flickrtimemap_menu() {
  $items['user/flickrrippr/%/timemap'] = array(
    'page callback' => 'flickrtimemap_user_page',
    'page arguments' => array(2),
    'title' => 'Flickr Time Map',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('view user flickr timemaps'),
  );
  $items['flickr/groups/%/timemap'] = array(
    'page callback' => 'flickrtimemap_group_page',
    'page arguments' => array(2),
    'title' => 'Flickr Time Map',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('view group flickr timemaps'),
  );
  $items['flickr/tags/%/timemap'] = array(
    'page callback' => 'flickrtimemap_tag_page',
    'page arguments' => array(2),
    'title' => 'Flickr Time Map',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('view tag flickr timemaps'),
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function flickrtimemap_perm() {
  return array('view user flickr timemaps', 'view group flickr timemaps', 'view tag flickr timemaps');
}

function flickrtimemap_user_page($uid) {
  $result = db_query("SELECT *  FROM {flickrgeo} g INNER JOIN {flickrphotos} p ON g.nid = p.nid LIMIT 1000", $start, $end);
  while($node = db_fetch_object($result)) {
    $items[] = $node;
  }
  return flickrtimemap_timemap($items);
}

function flickrtimemap_group_page($flickrgroup_id) {
  return '';
}

function flickrtimemap_tag_page($tag) {
  return '';
}



/**
 * Page call back
 */
function flickrtimemap_timemap($items) {
  drupal_set_html_head('<script src="http://maps.google.com/maps?file=api&v=2&key='. variable_get('googlemap_api_key', '') .'" type="text/javascript"></script>');
  drupal_set_html_head('<script src="http://static.simile.mit.edu/timeline/api/timeline-api.js" type="text/javascript"></script>');
  $timemapjs = url(drupal_get_path('module', 'flickrgeo') .'/js/timemap_full.pack.js');
  drupal_set_html_head('<script src="'. $timemapjs .'" type="text/javascript"></script>');
//   drupal_set_html_head('<link href="http://timemap.googlecode.com/svn/trunk/examples/examples.css" type="text/css" rel="stylesheet"/>');
  $timemapcss = url(drupal_get_path('module', 'flickrgeo') .'/css/map.css');
  drupal_set_html_head('<link href="'. $timemapcss .'" type="text/css" rel="stylesheet"/>');


  $output .= '
      <style>
    div#timelinecontainer{ height: 300px; }
    div#mapcontainer{ height: 500px; }
    </style>
    <div id="timemap">
      <div id="timelinecontainer">
        <div id="timeline"></div>
      </div>
      <div id="mapcontainer">
        <div id="map"></div>
      </div>
    </div>';
    $output .= '<script>$(document).ready(function() { timemapLoad() });</script>';


  $js = <<< STR

<script type="text/javascript">
function timemapLoad() {
    tm = TimeMap.init({
        mapId: "map",               // Id of map div element (required)
        timelineId: "timeline",     // Id of timeline div element (required)
        options: {
            eventIconPath: "../images/"
        },
        datasets: [
            {
                id: "photos",
                title: "Photos",
                theme: "orange",
                // note that the lines below are now the preferred syntax
                type: "basic",
                options: {
                    items: [
STR;

//      drupal_seT_message("$start to $end");

        foreach($items as $timemapthing) {
          $js .= flickrtimemap_json($thingmapthing);
        }

$js .= <<< STR
                    ]
                }
            }
        ],
        bandIntervals: [
            Timeline.DateTime.MONTH,
            Timeline.DateTime.YEAR
        ],
        scrollTo: "latest",
    });
}
    // manipulate the timemap further here if you like</script>
STR;
  drupal_set_html_head($js);


  return $output;
}

function flickrgeo_timemap_json($node) {
  $title = str_replace('"', '\"', $node->title);
  $link = str_replace('"', '\"', l($node->title, 'node/'. $node->nid));
  $start = $node->date_taken;
//   $end = date('Y-m-d', $start + (60*60*24));
  $lon = check_plain($node->longitude);
  $lat = check_plain($node->latitude);
  $node->flickr_photo = (array)$node;
  $thumb = str_replace('"', '\"', theme('image', flickrrippr_path($node, 's'),$node->title, $node->title, array(), FALSE));
  $js = <<< STR
                        {
                          "start" : "$start",
        "end": "$start",
                          "point" : {
                              "lat" : $lat,
                              "lon" : $lon
                           },
                          "title" : "$title",
                          "options" : {
                            // set the full HTML for the info window
                            "infoHtml": "<div class='custominfostyle'>$link<br/>$thumb</div>"
                          }
                        },
STR;
  return $js;
}